# Streamlit Secrets Configuration
GOOGLE_SHEETS_CREDENTIALS = "config/secrets/google_sheets_service.json"
GOOGLE_TTS_CREDENTIALS = "config/secrets/google_tts_service.json"
BACKEND_URL = "http://localhost:9000"
WEBHOOK_SECRET = "n8n_s3cR3t_p@s5phr@s3_f0R_p1p3l1n3"

# Google Sheets Configuration
GOOGLE_SHEETS_ID = "1Ej4Ej4Ej4Ej4Ej4Ej4Ej4Ej4Ej4Ej4Ej4Ej4"

# API Keys (add your actual keys here)
OPENAI_API_KEY = "your-openai-key-here"
ELEVENLABS_API_KEY = "your-elevenlabs-key-here"
STABILITY_API_KEY = "your-stability-key-here"
